config/routes.rb
Rails.application.routes.draw do
  get "/", to: "merchandises#index"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/sessions", to: "sessions#new"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/auth/facebook/callback", to: 'sessions#book_login'
  post "/merchandises/filter", to: 'merchandises#filter', as: 'filter'
  resources :sales
  resources :merchandise_reviews, only: [:new, :create, :edit, :update]

  resources :merchandises do
    resources :sales, only: [:new, :create]
  end

  resources :users do
    resources :sales, :merchandises, only: [:index, :show]
    resources :merchandise_reviews
  end

  resources :creators do
    resources :sales, :merchandises, only: [:index, :show, :new, :create]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/merchandises_controller.rb
class MerchandisesController < ApplicationController
    layout :set_layout
    before_action :find_merch, only: [:show, :edit, :update, :delete]

        
    def filter
        @merchandise_categories = MerchandiseCategory.all
        @merchandises = Merchandise.by_category(params[:category])

        render "merchandises/index"
    end

    def index
        @merchandise_categories = MerchandiseCategory.all
        if params[:creator_id]
            @merchandises = Merchandise.by_creator(params[:creator_id])
        else
            @merchandises = Merchandise.all
        end
    end

    def show
        @reviews = @merchandise.merchandise_reviews.last(5)
        @review = @merchandise.merchandise_reviews.build
    end

    def new
        if params[:creator_id] && session[:creator_id] == params[:creator_id].to_i
            creator = Creator.find_by(id: params[:creator_id])
            @merchandise = creator.merchandises.build
        else
            redirect_to '/'
        end
    end

    def create
        creator = current_creator
        @merchandise = creator.merchandises.build(merch_params)
        if @merchandise.save
            redirect_to merchandise_path(@merchandise)
        else
            render "merchandises/new"
        end
    end

    def edit
    end

    def update
        if @merchandise.update(merch_params)
            redirect_to merchandise_path(@merchandise)
        else
            render :edit
        end
    end

    def delete
        @merchandise.delete
        redirect_to merchandises_path
    end


    private

    def find_merch
        @merchandise = Merchandise.find(params[:id])
    end

    def merch_params
        params.require(:merchandise).permit(:title, :description, :price, :creator_id ,:merchandise_category_id)
    end

end

app/helpers/merchandises_helper.rb
module MerchandisesHelper

    def creator_name
        self.cretor.username
    end

end

app/views/merchandises/_form.html.erb
<div class="card">
    <%= form_for @merchandise, class: "card" do |f| %>
        <%= f.text_field :title, placeholder: "Title" %>
        <%= f.collection_select :merchandise_category_id, MerchandiseCategory.all, :id, :name, placeholder: "Category" %>
        <%= f.text_area :description, placeholder: "Description" %>
        <%= f.text_field :price, placeholder: "Price" %>
        <%= f.submit "Sell It!!" %>
    <% end %>
</div>

app/views/merchandises/edit.html.erb
<%= render partial: "layouts/errors", locals: {model: @merchandise} %>
<%= render partial:"form" %>

app/views/merchandises/index.html.erb
<%= form_tag filter_path  %>
<%= select_tag "category", options_from_collection_for_select(@merchandise_categories, :id, :name) %>
<%= submit_tag "Filter" %>


<% @merchandises.each do |merch| %>
    <div class="container">
        <%= link_to merch.title, merchandise_path(merch)%>
        <h4>$<%= merch.price %></h4>
        <p><%= merch.description %></p>
        <p><%= link_to merch.creator_name, creator_path(merch.creator)%></p>
    </div>
<% end %>

app/views/merchandises/new.html.erb
<h3>Add your item's info here, and it will be added to your storefront.</h3>

<%= render partial: "layouts/errors", locals: {model: @merchandise} %>
<%= render partial: "form" %>

app/views/merchandises/show.html.erb
<h2><%= @merchandise.title %><br>
    Price: <%= @merchandise.price %>
</h2>
<p>Sold By: <%= link_to @merchandise.creator_name, creator_path(@merchandise.creator)%><br>
<%= @merchandise.description %>

<% if current_creator && current_creator.id == params[:creator_id].to_i %>
    <%= button_to "Edit Item", edit_merchandise_path(@merchandise), method: "get" %>
    <%= button_to "Delete Item", merchandises_path(@merchandise), method: :delete %>
<% elsif current_user %>
    <%= button_to "Buy", new_merchandise_sale_path(@merchandise), method: "get" %>
<% end %>
<p>---------------------------------------</p>
<h1>Reviews: <%= @reviews.length %></h1>
<% @reviews.each do |review| %>
<h4><%= review.title %></h4>
<p><%= review.body %> </p>
<p>Rating: <strong><%= review.rating %></strong></p>
<% end %>

<% if current_user && current_user.merchandises.include?(@merchandise) %>
<h3>It seems you've purchased this product in the past!<br>
Please write a review:</h3>
    <%= form_for @review do |f| %>
        Title<br>
            <%= f.text_field :title %><br>
        Review<br>
            <%= f.text_area :body %><br>
        Rating(1-5)<br>
            <%= f.text_field :rating %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :merchandise_id, value: @merchandise.id %>
        <%= f.submit %>
    <% end %>
<% end %>