config/routes.rb
Rails.application.routes.draw do
  get "/", to: "merchandises#index"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/sessions", to: "sessions#new"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/auth/facebook/callback", to: 'sessions#book_login'
  post "/merchandises/filter", to: 'merchandises#filter', as: 'filter'
  resources :sales
  resources :merchandise_reviews, only: [:new, :create, :edit, :update]

  resources :merchandises do
    resources :sales, only: [:new, :create]
  end

  resources :users do
    resources :sales, :merchandises, only: [:index, :show]
    resources :merchandise_reviews
  end

  resources :creators do
    resources :sales, :merchandises, only: [:index, :show, :new, :create]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/creator.rb
class Creator < ApplicationRecord
    has_many :merchandises
    has_many :sales, through: :merchandises
    has_many :categories, through: :merchandises
    validates :email, :username, presence: true
    validates :email, :username, uniqueness: true
    validates :promo_discount, inclusion: {in: (0..100)}
    has_secure_password
    

    def find_creator_by_username
        @creator = Creator.find_by(username: params[:username])
    end

    def find_creator_by_email
        @creator = Creator.find_by(email: params[:email])
    end

    def merchandise_count
        self.merchandises.length
    end

end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
    layout :set_layout
    before_action :find_creator, only: [:show, :edit, :update, :delete]
    
    def index
        @creators = Creator.all
    end

    def show     
    end

    def new
        @creator = Creator.new
    end

    def create
        @creator = Creator.new(creator_params)
        if @creator.save
            session[:creator_id] = @creator.id
            redirect_to creator_path(@creator)
        else
            @creator = Creator.create(creator_params)     
            render "creators/new"
        end
    end

    def edit     
    end

    def update
        if @creator.update(creator_params)
            redirect_to creator_path(@creator)
        else
            render :edit
        end
    end

    def delete
        @creator.destroy
        redirect_to logout_path
    end

    # def current_creator
    #     Creator.find_by(id: session[:creator_id])
    # end

    private
    def find_creator
        @creator = Creator.find_by(id: params[:id])
    end
    def creator_params
        params.require(:creator).permit(:email, :username, :password, :about, :age, :location, :promo_code, :promo_discount)
    end
end

app/helpers/creators_helper.rb
module CreatorsHelper

    def current_creator
        Creator.find_by(id: session[:creator_id])
    end
end

app/views/creators/_form.html.erb
<div class="card">
    <%= form_with model: model, local: :true do |f|  %>
        <%= f.text_field :username, placeholder: "Username"%>
        <%= f.text_field :email, placeholder: "Email"%>
        <%= f.password_field :password, placeholder: "Password"%>
        <%= f.text_field :about, placeholder: "Write a description of your store here. What do you sell? Why? Is it home made?"%>
        <%= f.text_field :location, placeholder: "location"%><br>
        <%= f.submit button %>
    <% end %>
</div>

app/views/creators/edit.html.erb
<%= render partial: "layouts/errors", locals: { model: @creator} %>
<%= render partial: "form", locals: { button: "Edit", model: @creator } %>

app/views/creators/index.html.erb
<h1>Creator Index</h1>

<% @creators.each do |creator|%>
    <h4><%= link_to creator.username, creator_path(creator) %></h4>
    <p>Items:<%= link_to creator.merchandise_count, creator_merchandises_path(creator) %></p>
<% end %>

app/views/creators/new.html.erb
<%= render partial: "layouts/errors", locals: { model: @creator } %>
<%= render partial: "form", locals: { model: @creator, button: "Start Selling!" } %>

app/views/creators/show.html.erb
<%= render partial: "users/info", locals: {model: @creator} %>

<% if current_creator && current_creator.id == @creator.id %>
    <div class="creator-buttons">
        <%= button_to "Edit Profile", edit_creator_path(@creator), method: "get" %>
        <%= button_to "Add Merchandise", new_creator_merchandise_path(@creator.id), method: "get" %>
    </div>
<% end %>

<% @creator.merchandises.last(5).each do |merch|%>
    <div class="card">
        <h3><%= link_to merch.title, creator_merchandise_path(@creator, merch) %></h3>
        <h3><%= merch.price %></h3>
        <p><%= merch.description%></p>
    </div>
<% end %>