config/routes.rb
Rails.application.routes.draw do
  get "/", to: "merchandises#index"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/sessions", to: "sessions#new"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/auth/facebook/callback", to: 'sessions#book_login'
  post "/merchandises/filter", to: 'merchandises#filter', as: 'filter'
  resources :sales
  resources :merchandise_reviews, only: [:new, :create, :edit, :update]

  resources :merchandises do
    resources :sales, only: [:new, :create]
  end

  resources :users do
    resources :sales, :merchandises, only: [:index, :show]
    resources :merchandise_reviews
  end

  resources :creators do
    resources :sales, :merchandises, only: [:index, :show, :new, :create]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
    belongs_to :merchandise
    belongs_to :user
    has_many :creators, through: :merchandises
    validates_presence_of :shipping_address
    
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
    layout :set_layout
    before_action :find_sale, only: [:show, :edit, :update, :delete]
    
    def index
        if params[:creator_id] && params[:creator_id].to_i == session[:creator_id]
            creator = Creator.find_by(id: params[:creator_id])
            sales = creator.merchandises.map do |merch|
                merch.sales
            end
            @sales = sales.flatten 

        elsif params[:user_id] && params[:user_id].to_i == session[:user_id]
            user = User.find_by(id: params[:user_id])
            @sales = user.sales
        else
            redirect_to '/'
        end  
    end
    
    def show
        if params[:creator_id] && params[:creator_id].to_i == session[:creator_id]
            creator = Creator.find_by(id: params[:creator_id])
            @sale = creator.sales.find_by(id:params[:id])
        elsif params[:user_id] && params[:user_id].to_i == session[:user_id]
            user = User.find_by(id: params[:user_id])
            @sale = user.sales.find_by(id:params[:id])
        else
            redirect_to '/'
        end  
    end

    def new
        if params[:merchandise_id]
            @sale= Sale.new
            @merchandise = Merchandise.find_by(id: params[:merchandise_id])
        else
            redirect_to '/'
        end
    end

    def create
        @sale = current_user.sales.build(sale_params)
        if @sale.save
            redirect_to user_sale_path(current_user, @sale)
        else 
            redirect_to new_merchandise_sale_path(params[:sale][:merchandise_id])
        end
    end


    private
    def sale_params
        params.require(:sale).permit(:user_id, :merchandise_id, :promo_code, :tip, :shipping_address)
    end

    def current_user
        User.find_by(id: session[:user_id])  #!current_user defined multiple times. Where does it need to be?
    end

    def find_sale
        @sale = Sale.find_by(id: params[:id])
    end
end

app/helpers/sales_helper.rb
module SalesHelper

    def has_sales?
        current_creator.sales.any?
    end

    def merch_price(sale)
        Merchandise.find_by(id: sale.merchandise_id).price
    end

    def merch_title(sale)
        Merchandise.find_by(id: sale.merchandise_id).title
    end

    def merch_title(sale)
        Merchandise.find_by(id: sale.merchandise_id).title
    end

    def merch_creator_name(sale)
        Merchandise.find_by(id: sale.merchandise_id).creator.username
    end

    def merch_total(sale)
        m = Merchandise.find_by(id: sale.merchandise_id)
        m.price + (sale.tip ||= 0)
    end
end

app/views/sales/index.html.erb
<%#iterates current_users sales and displays info for each sale.%>

<h1> Recent Transactions By <%= !!current_user ? current_user.username : current_creator.username %></h1>

<% @sales.reverse.each do |sale| %>
    <% if current_user %>
        <h1>SALE #<%=link_to sale.id, user_sale_path(current_user.id, sale) %></h1>
    <% elsif current_creator %>
        <h1>SALE #<%= link_to sale.id, creator_sale_path(current_creator.id, sale) %></h1>
    <% end %>
        <h2><%= sale.merchandise.title %></h2>
        <h2><%= merch_price(sale) %></h2>
        <p>Sold By: <%=merch_creator_name(sale)%></p>
<% end %>

app/views/sales/new.html.erb
<h1>New Sale</h1>
<%= render partial: "layouts/errors", locals: { model: @sale } %>
<p><%= @merchandise.title %> --
<%= @merchandise.price %></p>
<%= form_for @sale do |f|%>
<%# <%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :merchandise_id, value: params[:merchandise_id] %>
Tip Amount(optional)<%= f.text_field :tip %>
<p>Please Enter The Shipping Address:</p>
<p><%= f.text_field :shipping_address %></p>
<p><%= f.submit "Place Order" %></p>
<% end %>

app/views/sales/show.html.erb
<h1>SALE #<%= @sale.id %></h1>
<h1> <%= link_to merch_title(@sale), merchandise_path(@sale.merchandise_id) %></h1>
<br>
<h2>Price: <%= merch_price(@sale) %></h2>
<h2>Tip: <%= @sale.tip %></h2>
<br>
<h2>Total: <%= merch_total(@sale) %></h2>
<p>Ship To: <%= @sale.shipping_address %></p>
<p>Sold By: <%=link_to merch_creator_name(@sale), creator_path(@sale.merchandise.creator)%></p>