config/routes.rb
Rails.application.routes.draw do
  get "/", to: "merchandises#index"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/sessions", to: "sessions#new"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/auth/facebook/callback", to: 'sessions#book_login'
  post "/merchandises/filter", to: 'merchandises#filter', as: 'filter'
  resources :sales
  resources :merchandise_reviews, only: [:new, :create, :edit, :update]

  resources :merchandises do
    resources :sales, only: [:new, :create]
  end

  resources :users do
    resources :sales, :merchandises, only: [:index, :show]
    resources :merchandise_reviews
  end

  resources :creators do
    resources :sales, :merchandises, only: [:index, :show, :new, :create]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h2>
      <%= pluralize(model.errors.count, "error") %>
      prohibited this <%= model.class %> from being saved:
    </h2>
 
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <h4> Created By TH-Programming </h4>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreatedToSell</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <h1><%= link_to "CreatedToSell", "/"%></h1>

    <ul class = "nav">
      <li><%=link_to "LogIn", login_path%>
      <li><%= link_to "User Signup", new_user_path %>
      <li><%= link_to "Creator Signup", new_creator_path %>
    </ul>
  </header>

  <main>  
    <%= yield %>
  </main>

  <%= render partial:"/layouts/footer" %>
  </body>
</html>

app/views/layouts/creator.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreatedToSell</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "CreatedToSell", "/"%></h1>
      
      <ul class = "nav">
        <li><%= link_to "My Storefront", creator_path(current_creator) %>
        <li><%= link_to "New Listing", new_creator_merchandise_path(current_creator) %>
        <li><%= link_to "Sales", creator_sales_path(current_creator) %>
        <li><%= link_to "Logout", logout_path %>
      </ul>
    </header>

    <main>  
      <%= yield %>
    </main>

    <%= render partial:"/layouts/footer" %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreatedToSell</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <h1><%= link_to "CreatedToSell", "/"%></h1>

    <ul class = "nav">
      <li> <%= link_to "Home", user_path(current_user)  %>
      <li> <%= link_to "Find Merchandise", merchandises_path %>
      <li> <%= link_to "Creators", creators_path %>
      <li> <%= link_to "Sale History", user_sales_path(current_user) %>
      <li> <%= link_to "Logout", logout_path %>
    </ul>
  </header>

  <main>  
    <%= yield %>
  </main>

  <%= render partial:"/layouts/footer" %>

  </body>
</html>